# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6f746ab5e83ad20d41acf2802f0067e9a5db6c269cc4981d1334b4c6d0cad1229effd42802f104af994802460b33b1ff322a564d44f20ca2e0bf225ec324edf5

test:
  secret_key_base: cd8b918cb4efcec1373b8077a9878158acafafca5fa2792def87882f9f9830315f6a0d00c8ed2bfe89c61546cfcb8960547df27a1f3fd911f41c7c2c82e7afaa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
